
name: Build RPM

on:
  pull_request:
    paths:
      - '*.spec'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build-rpm:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [
          "ubuntu-24.04",
          "ubuntu-24.04-arm"
        ]
        container: [
          "almalinux:9",
          "almalinux:10",
          "almalinux:10-kitten",
          "quay.io/centos/centos:stream9",
          "quay.io/centos/centos:stream10"
        ]
    runs-on: ${{ matrix.runs-on }}
    container:
      image: ${{ matrix.container }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install RPM build tools
        run: |
          dnf -q install -y epel-release
          dnf -q --refresh makecache -y
          dnf -q --setopt='install_weak_deps=False' install -y @"RPM Development Tools" findutils dnf-plugins-core

      - name: Set up RPM build environment
        run: |
          rpmdev-setuptree

      - name: Copy spec file
        run: |
          cp uuu.spec ~/rpmbuild/SPECS/

      - name: Download source files
        run: |
          cd ~/rpmbuild/SOURCES
          rpmdev-spectool -g ../SPECS/uuu.spec

          find . -mindepth 1 -maxdepth 1 -type f -executable

      - name: Install build dependencies
        run: |
          dnf build-dep -y ~/rpmbuild/SPECS/uuu.spec

      - name: Build RPM
        run: |
          cd ~/rpmbuild/SPECS
          rpmbuild -ba \
            --nodebuginfo \
            ~/rpmbuild/SPECS/uuu.spec

      - name: List built RPMs
        run: |
          find ~/rpmbuild/RPMS -type f -name "*.rpm" -ls
          find ~/rpmbuild/RPMS -type f -name "*.rpm" -exec rpm -qpi {} \+
          find ~/rpmbuild/RPMS -type f -name "*.rpm" -exec rpm -qpl {} \+

